= parinfer-rust

Infer parentheses for Clojure, Lisp and Scheme.

https://github.com/eraserhd/parinfer-rust

A full-featured, super fast implementation of
https://shaunlebron.github.io/parinfer/[Shaun Lebron’s parinfer]. This repo
comes with Vim plugin files that work with Vim8 and Neovim. The Rust library
can be called from other editors that can load dynamic libraries.

This plugin, unlike others available for Vim, implements "smart" mode. Rather
than switching between "paren" mode and "indent" mode, parinfer uses
information about how the user is changing the file to decide what to do.

== Installing

Dependencies:

* https://www.rust-lang.org/en-US/install.html[rust] >= 1.36
* `clang` and `libclang-dev` packages or equivalent for your OS

=== Stand-alone

If you just want to run `parinfer-rust` from the command-line:

....
$ cargo build --release
$ cargo install
....

=== Vim and Neovim

==== `+pathogen+`

If you are using Tim Pope’s `+pathogen+`:

....
$ cd ~/.vim/bundle
$ git clone git@github.com:eraserhd/parinfer-rust.git
$ cd ~/.vim/bundle/parinfer-rust
$ cargo build --release
....

==== `+vim-plug+`

[source,viml]
----
Plug 'eraserhd/parinfer-rust'
----

Then, build project using cargo:

....
$ cd /path/to/parinfer-rust
$ cargo build --release
....

Or, with optional automatic recompilation on update:

[source,viml]
----
Plug 'eraserhd/parinfer-rust', {'do':
        \  'cargo build --release'}
----

If you are a NixOS user, you can use this command instead:
[source,viml]
----
Plug 'eraserhd/parinfer-rust', {'do':
        \ 'nix-shell --run \"cargo build --release \"'}
----

=== Kakoune

==== `+plug.kak+`

Add this to your `+kakrc+`

[source,kak]
----
plug "eraserhd/parinfer-rust" do %{
    cargo install --force --path .
} config %{
    hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
        parinfer-enable-window -smart
    }
}
----

Re-source your `+kakrc+` or restart Kakoune. Then run `+:plug-install+`.
`+plug.kak+` will download, build and install plugin for you. Optionally
add `+cargo clean+` line to the `+do+` block to clean plugin from build
files, thus making it load a bit faster.

==== Manual

....
$ cd ~/my-projects
$ git clone git@github.com:eraserhd/parinfer-rust.git
$ cd parinfer-rust
$ make install
$ cargo build --release
$ cargo install
....

Add this to your `+kakrc+`

[source,kak]
----
hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
    parinfer-enable-window -smart
}
----

=== Emacs

To install parinfer-rust for Emacs follow the instructions at
https://github.com/justinbarclay/parinfer-rust-mode#installing[parinfer-rust-mode.el]

== Building WebAssembly

WebAssembly currently needs the ``nigthly'' toolchain:

....
$ rustup update
$ rustup install nightly
$ rustup target add wasm32-unknown-unknown --toolchain nightly
$ cargo +nightly install cargo-web
....

It can then be built with:

....
$ cargo +nightly web build --release
....

== Tests

The CI server uses [Nix](https://nixos.org/nix/download.html) to make
reproducible build and test environments.  It's a good idea to run tests with
it.

....
$ cargo test                            # Run the native tests
$ cargo +nightly web test               # Test the WebAssembly version
$ vim --clean -u tests/vim/run.vim      # Test against locally-installed vim
$ nix-build release.nix                 # Run everything that CI does
$ nix-build release.nix -A vim-tests    # Test against Vim packages by Nix
$ nix-build release.nix -A neovim-tests # Test against Vim packages by Nix
....

Vim tests are in a nice, readable format in `+tests/vim/test-cases.md+`.
Please add tests for any new features (or even old ones!).
You can set the `+VIM_TO_TEST+` environment variable to Vim’s path to test weird or different builds.

== Contributors

This wouldn’t be possible without the work of others:

* Shaun Lebron - Inventing parinfer and doing the math.
* Case Nelson - Writing the nvim-parinfer, from which VimL code and some
  inspiration was stolen.
* Justin Barclay - Emacs module.

== License

link:LICENSE.md[ISC License]
