setglobal nocompatible nomore cpo-=C

filetype on
syntax on
try
  source plugin/parinfer.vim
catch
  echohl ErrorMsg
  echo "Error loading Vim plugin:" v:exception
  echohl None
  cquit
endtry

" Kinda simulate vim-fireplace command-line window
au CmdWinEnter @ setlocal filetype=clojure
au CmdWinLeave @ setlocal filetype< omnifunc<
