name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: macOS-latest
            rust: stable
            artifact_name: libparinfer_rust.dylib
            release_name: parinfer-rust-darwin.so
            target: "aarch64-apple-darwin"
          - os: windows-latest
            rust: stable
            artifact_name: parinfer_rust.dll
            release_name: parinfer-rust-windows.dll
            target: "x86_64-pc-windows-msvc"
          - os: ubuntu-latest
            rust: stable
            artifact_name: libparinfer_rust.so
            release_name: parinfer-rust-linux.so
            target: "x86_64-unknown-linux-gnu"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target  }}
      - name: Build the crate for release
        run: cargo build --release --target ${{ matrix.target }} --features emacs
      - name: Run tests
        if: matrix.os != 'windows-latest'
        run: cargo test --verbose
      - name: Rename library
        run: cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.release_name }}
      - name: Upload libraries to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.release_name }}
